### ISSUE TITLE
Drop Down not working in function --> Stan Hacks 2 Product

### ISSUE THREAD

**Issue by KasinadhuniProgrammer** [KasinadhuniProgrammer/HackTacks#2]
Drop Down menu not working in the first function in code. This leaves us with two options, we can either try to figure out how, or keep the whole game on one screen. If we keep the whole game on one screen then we will have to check in with the design team.

**Comment by KasinadhuniProgrammer** [comment]
Code is in GitHub and the error is commented

**Comment by KasinadhuniProgrammer** [comment]
I assigned our whole team to this issue, @ProdigySammy21 @KasinadhuniProgrammer @padamoham @Awesomeape

**Comment by ProdigySammy21** [comment]
So what are we supposed to do about that. IT really should be assigned only to yourself because you're the only on that can fix it. Like, if there is a problem in the design, Chinna Satvik and Arush get assigned the issue and change that, and if there is a problem with the front end developing, then assign the issue to me and I will fix it. The same way, of there is a problem in the back end developing, then you should be assigned the error. Not all of us.
